# Generated by Django 6.0 on 2025-12-22 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    def forwards_convert_positions(apps, schema_editor):
        User = apps.get_model('accounts', 'User')
        Position = apps.get_model('accounts', 'Position')

        # Create Position records from existing distinct non-empty user.position strings
        distinct_names = (
            User.objects
            .exclude(position__isnull=True)
            .exclude(position__exact='')
            .values_list('position', flat=True)
            .distinct()
        )
        for name in distinct_names:
            Position.objects.get_or_create(name=name)

        # Map users to new FK field based on name, set None for blanks
        for user in User.objects.all():
            pos_name = getattr(user, 'position', None)
            if pos_name is None or pos_name == '':
                # ensure nulls for empty values
                User.objects.filter(id=user.id).update(position_new_id=None)
            else:
                try:
                    pos_obj = Position.objects.get(name=pos_name)
                    User.objects.filter(id=user.id).update(position_new_id=pos_obj.id)
                except Position.DoesNotExist:
                    # Fallback: create and assign if a race or missing
                    pos_obj = Position.objects.create(name=pos_name)
                    User.objects.filter(id=user.id).update(position_new_id=pos_obj.id)

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        # Add a temporary FK field to migrate data safely
        migrations.AddField(
            model_name='user',
            name='position_new',
            field=models.ForeignKey(
                to='accounts.position',
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name='employees'
            ),
        ),
        migrations.RunPython(forwards_convert_positions, migrations.RunPython.noop),
        # Remove old CharField
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        # Rename temporary field to final name
        migrations.RenameField(
            model_name='user',
            old_name='position_new',
            new_name='position',
        ),
    ]
