# Generated by Django 6.0 on 2025-12-22 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_position_alter_user_position'),
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='employee_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='branches.branch'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
