# Generated by Django 5.2.8 on 2025-12-24 08:51

from django.db import migrations, models


SENTINEL_PREFIX = "__EMPTY__"
DUP_PREFIX = "__DUP__"


def mark_blanks_with_sentinel(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Replace blank values with a unique sentinel (avoids NOT NULL & UNIQUE issues pre-alter)
    for u in User.objects.all():
        val = getattr(u, 'employee_number', None)
        if isinstance(val, str) and val.strip() == "":
            sentinel = f"{SENTINEL_PREFIX}{u.pk}"
            User.objects.filter(pk=u.pk).update(employee_number=sentinel)

    # Ensure uniqueness: for duplicate non-empty values, keep the first and mark others with DUP sentinel
    seen = set()
    for u in User.objects.exclude(employee_number__isnull=True):
        val = u.employee_number
        if not isinstance(val, str):
            continue
        trimmed = val.strip()
        if trimmed == "":
            continue
        key = trimmed
        if key in seen:
            User.objects.filter(pk=u.pk).update(employee_number=f"{DUP_PREFIX}{u.pk}")
        else:
            seen.add(key)


def unset_sentinel_to_null(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    # Convert sentinel values back to NULL after field allows nulls
    for u in User.objects.filter(employee_number__startswith=SENTINEL_PREFIX):
        User.objects.filter(pk=u.pk).update(employee_number=None)
    for u in User.objects.filter(employee_number__startswith=DUP_PREFIX):
        User.objects.filter(pk=u.pk).update(employee_number=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_employee_branch'),
    ]

    operations = [
        migrations.RunPython(mark_blanks_with_sentinel, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.RunPython(unset_sentinel_to_null, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
