# Generated by Django 6.0 on 2025-12-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_position_id_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_competency_level',
            field=models.CharField(blank=True, choices=[('CL1', 'Awareness'), ('CL2', 'Knowledge'), ('CL3', 'Skill'), ('CL4', 'Master')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='total_competency_points',
            field=models.IntegerField(default=0),
        ),
    ]
