# Generated by Django 6.0 on 2025-12-30 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_current_competency_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='cl1_min_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='cl2_min_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='cl3_min_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='position',
            name='cl4_min_points',
            field=models.IntegerField(default=0),
        ),
    ]
