# Generated by Django 6.0 on 2026-01-04 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_position_cl1_min_points_position_cl2_min_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        # Clean up invalid position references before enforcing FK constraints
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='accounts.position'),
        ),
        migrations.RunSQL(
            sql=(
                "UPDATE accounts_user SET position_id = NULL "
                "WHERE position_id NOT IN (SELECT id FROM accounts_position)"
            ),
            reverse_sql=(
                "-- No reverse data migration needed for cleanup"
            ),
        ),
    ]
