# Generated by Django 5.2.8 on 2026-01-05 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_position_department_alter_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_competency_level',
        ),
        migrations.RemoveField(
            model_name='user',
            name='total_competency_points',
        ),
    ]
