# Generated by Django 6.0 on 2026-01-05 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_current_competency_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='min_required_level',
            field=models.CharField(choices=[('CL0', 'None'), ('CL1', 'Awareness'), ('CL2', 'Knowledge'), ('CL3', 'Skill'), ('CL4', 'Master')], default='CL1', help_text='Minimum competency level required for users in this position.', max_length=3),
        ),
    ]
