# Generated by Django 6.0 on 2026-05-14 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_notification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='accounts_no_user_id_a4ff2e_idx',
            old_name='accounts_no_user_id_isread_idx',
        ),
    ]
