# Generated by Django 6.0 on 2026-05-21 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_accounts_no_user_id_isread_idx_accounts_no_user_id_a4ff2e_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('EXAM_GRADED', 'Exam graded'), ('EXAM_PASSED', 'Exam passed'), ('EXAM_FAILED', 'Exam failed'), ('NEW_HIRE_TASKS', 'New hire tasks'), ('PROMOTION_TASKS', 'New competencies after promotion'), ('COMPETENCY_EXPIRING', 'Competency expiring soon'), ('COMPETENCY_EXPIRED', 'Competency expired'), ('GENERIC', 'Notification')], default='GENERIC', max_length=20),
        ),
    ]
