# Generated by Django 6.0 on 2026-06-04 06:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_notification_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='employees/attachments/')),
                ('kind', models.CharField(choices=[('SIGNED_SCORE', 'Signed score sheet'), ('PHOTO', 'Photo'), ('ID', 'ID / document'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(help_text='The employee this file belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to=settings.AUTH_USER_MODEL)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_attachments_uploaded', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['employee', 'kind'], name='accounts_em_employe_f94b1b_idx')],
            },
        ),
    ]
