# Generated by Django 6.0 on 2026-06-04 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_employeeattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='manual_level_override',
            field=models.CharField(blank=True, choices=[('CL0', 'None'), ('CL1', 'Awareness'), ('CL2', 'Knowledge'), ('CL3', 'Skill'), ('CL4', 'Master')], help_text='If set, overrides the auto-computed competency level. Used when a manager assigns a level via a verbal assessment that an admin has approved.', max_length=3, null=True),
        ),
    ]
