"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import dj_database_url

from pathlib import Path
import os
from datetime import timedelta


BASE_DIR = Path(__file__).resolve().parent.parent

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# In production, set DJANGO_SECRET_KEY in the environment. The fallback
# value is only used for local development and must NOT be used in prod.
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-+%3fn+%5t6xcod7m$*3a(=4(kp02x=d5$@ig@v%2l9gzg)i@tq',
)

# SECURITY WARNING: don't run with debug turned on in production!
# Set DJANGO_DEBUG=0 in production environments.
DEBUG = os.environ.get('DJANGO_DEBUG', '1') == '1'

# Allow all hosts during development to enable LAN/mobile testing
# Comma-separated env var. Always include the Render service URL once
# you know it, e.g. 'training-system.onrender.com'.
_ALLOWED_HOSTS_ENV = os.environ.get('DJANGO_ALLOWED_HOSTS', '')
ALLOWED_HOSTS = (
    ['*'] if DEBUG else [h.strip() for h in _ALLOWED_HOSTS_ENV.split(',') if h.strip()]
)
# Render injects its hostname into RENDER_EXTERNAL_HOSTNAME when running there.
_render_host = os.environ.get('RENDER_EXTERNAL_HOSTNAME')
if _render_host and _render_host not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(_render_host)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'branches', 'accounts', 'training',
    'rest_framework.authtoken',

]

# Allow login with employee_number or username
AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmployeeNumberOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    # Throttle classes for sensitive endpoints (e.g. login).
    # Use scoped throttle on the login view; defaults apply project-wide.
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.ScopedRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'core' / 'templates',
            BASE_DIR / 'accounts' / 'templates',
            BASE_DIR / 'frontend' / 'dist',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'



# Database
# Use PostgreSQL on Render (production), SQLite locally
import dj_database_url

if os.environ.get('RENDER', None):
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
AUTH_USER_MODEL = 'accounts.User'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = BASE_DIR / "staticfiles"


# Use BigAutoField by default to avoid primary key warnings
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Session-based login for temporary frontend pages
# NOTE: web/exams/ URLs are commented out in core/urls.py since we moved to
# React-only. Redirect to the site root instead of a dead URL.
LOGIN_URL = '/accounts/login/'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/accounts/login/'

# CORS for local React dev server
CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
    'http://localhost:5174',
    'http://127.0.0.1:5174',
]

# Session cookies expire when browser closes
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# In development, allow all origins to simplify testing across devices on LAN
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True


# -----------------------------------------------------------------------------
# PRODUCTION HARDENING (only effective when DEBUG=False)
# -----------------------------------------------------------------------------

# Whitenoise: gzip + brotli pre-compressed copies of static files for prod.
# We use CompressedStaticFilesStorage rather than the *Manifest* variant
# because Vite already produces hash-keyed filenames (e.g.
# `assets/index-DfRSak.js`). The Manifest backend would try to rewrite
# references inside those files and break them; the plain Compressed
# backend just gzips them and serves them as-is, which is exactly what we
# want for a SPA bundle.
STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# CORS / CSRF trusted origins from env (comma-separated). Include the frontend
# domain if you split frontend and backend; if you serve them from one origin
# (the default Render config below) you can leave these empty.
_extra_origins = [o.strip() for o in os.environ.get('DJANGO_CORS_ORIGINS', '').split(',') if o.strip()]
CORS_ALLOWED_ORIGINS = list(set(CORS_ALLOWED_ORIGINS) | set(_extra_origins))
CSRF_TRUSTED_ORIGINS = [o.strip() for o in os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS', '').split(',') if o.strip()]
if _render_host:
    _https_render = f"https://{_render_host}"
    if _https_render not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_https_render)

if not DEBUG:
    # Render terminates TLS at the proxy and forwards HTTP to gunicorn.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 days
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_CONTENT_TYPE_NOSNIFF = True 

# WHERE THE REACT BUILD ENDS UP
# Vite outputs the production bundle to frontend/dist/. Adding that to
# STATICFILES_DIRS makes collectstatic copy the hashed JS/CSS chunks and
# index.html into STATIC_ROOT (= staticfiles/), where WhiteNoise serves
# them under /static/.
_FRONTEND_BUILD_DIR = BASE_DIR / "frontend" / "dist"
if _FRONTEND_BUILD_DIR.exists():
    STATICFILES_DIRS = list(STATICFILES_DIRS) + [_FRONTEND_BUILD_DIR]
