from django.urls import path
from training.views_frontend import (
    exams_list_page,
    take_exam_page,
    exam_result_page,
    publish_requirements_page,
    manager_dashboard_page,
    create_exam_page,
    manage_exam_questions_page,
     manager_sessions_page,
     grade_session_page,
    manage_requirements_page,
    manage_competencies_page,
    edit_competency_page,
    employee_dashboard_page,
    competency_detail_page,
    competency_file_action,
    manager_employee_lookup_page,
    expiring_competencies_page,
    grading_queue_page,
    employee_insights_page,
    admin_dashboard_page,
    reports_exports_page,
    export_compliance_csv,
    export_sessions_csv,
)

urlpatterns = [
    path("", exams_list_page, name="web-exams-list"),
    path("exam/<int:exam_id>/", take_exam_page, name="web-take-exam"),
    path("exam/result/<int:session_id>/", exam_result_page, name="web-exam-result"),
    path("publish/", publish_requirements_page, name="web-publish-requirements"),
    path("manager/", manager_dashboard_page, name="web-manager-dashboard"),
    path("manager/create/", create_exam_page, name="web-create-exam"),
    path("manager/manage/<int:exam_id>/", manage_exam_questions_page, name="web-manage-questions"),
     path("manager/sessions/", manager_sessions_page, name="web-manager-sessions"),
     path("manager/sessions/<int:session_id>/", grade_session_page, name="web-grade-session"),
    path("manager/requirements/", manage_requirements_page, name="web-manage-requirements"),
    path("manager/competencies/", manage_competencies_page, name="web-manage-competencies"),
    path("manager/competencies/<int:comp_id>/", edit_competency_page, name="web-edit-competency"),
    path("manager/employee/", manager_employee_lookup_page, name="web-manager-employee-lookup"),
    path("employee/", employee_dashboard_page, name="web-employee-dashboard"),
    path("employee/competency/<int:comp_id>/", competency_detail_page, name="web-competency-detail"),
    path("employee/competency/<int:comp_id>/file/<str:filetype>/<str:action>/", competency_file_action, name="web-competency-file"),
    # New manager features
    path("manager/expiring/", expiring_competencies_page, name="web-expiring-competencies"),
    path("manager/grading-queue/", grading_queue_page, name="web-grading-queue"),
    path("manager/insights/", employee_insights_page, name="web-employee-insights"),
    path("admin/", admin_dashboard_page, name="web-admin-dashboard"),
    path("manager/reports/", reports_exports_page, name="web-reports-exports"),
    path("manager/reports/export/compliance.csv", export_compliance_csv, name="web-export-compliance-csv"),
    path("manager/reports/export/sessions.csv", export_sessions_csv, name="web-export-sessions-csv"),
]
