# Generated by Django 5.2.8 on 2025-12-25 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_remove_exam_module_remove_result_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='external_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='modules/images/'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='modules/pdfs/'),
        ),
    ]
