# Generated by Django 6.0 on 2025-12-28 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0004_trainingmodule_external_link_trainingmodule_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='max_points',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='training.question'),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='selected_choices',
            field=models.ManyToManyField(blank=True, related_name='answers', to='training.questionchoice'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='training.examtemplate'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted'), ('GRADED', 'Graded'), ('EXPIRED', 'Expired')], default='IN_PROGRESS', max_length=20),
        ),
    ]
