# Generated by Django 6.0 on 2025-12-30 05:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_current_competency_level_and_more'),
        ('training', '0005_examanswer_created_at_question_max_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmodule',
            name='base_priority_points',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='exam_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='module', to='training.examtemplate'),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='frequency',
            field=models.CharField(choices=[('ONE_TIME', 'One time'), ('YEARLY', 'Yearly'), ('NEW_HIRE', 'New hire'), ('PROMOTION', 'Promotion'), ('OTHER', 'Other')], default='ONE_TIME', max_length=20),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='reference_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='trainingmodule',
            name='target_level',
            field=models.CharField(blank=True, choices=[('CL1', 'Awareness'), ('CL2', 'Knowledge'), ('CL3', 'Skill'), ('CL4', 'Master')], max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='PositionCompetencyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('required', models.BooleanField(default=True)),
                ('priority_points', models.PositiveIntegerField(default=0)),
                ('min_level_for_position', models.CharField(blank=True, choices=[('CL1', 'Awareness'), ('CL2', 'Knowledge'), ('CL3', 'Skill'), ('CL4', 'Master')], max_length=3, null=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_requirements', to='training.trainingmodule')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_requirements', to='accounts.position')),
            ],
            options={
                'unique_together': {('position', 'module')},
            },
        ),
        migrations.CreateModel(
            name='EmployeeCompetencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed')], default='NOT_STARTED', max_length=20)),
                ('best_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('points_earned', models.IntegerField(default=0)),
                ('last_taken_at', models.DateTimeField(blank=True, null=True)),
                ('attempts_count', models.PositiveIntegerField(default=0)),
                ('is_extra_assignment', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_records', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_records', to='training.trainingmodule')),
                ('position_requirement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='training.positioncompetencyrequirement')),
            ],
            options={
                'unique_together': {('employee', 'module')},
            },
        ),
    ]
