# Generated by Django 6.0 on 2026-01-04 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_position_department_alter_user_position'),
        ('training', '0006_trainingmodule_base_priority_points_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='employeecompetencyrecord',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeecompetencyrecord',
            name='period',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeecompetencyrecord',
            name='quarter',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='employeecompetencyrecord',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeecompetencyrecord',
            name='week',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='positioncompetencyrequirement',
            name='competency_level',
            field=models.CharField(blank=True, choices=[('CL1', 'Awareness'), ('CL2', 'Knowledge'), ('CL3', 'Skill'), ('CL4', 'Master')], max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='positioncompetencyrequirement',
            name='frequency',
            field=models.CharField(blank=True, choices=[('ONE_TIME', 'One time'), ('YEARLY', 'Yearly'), ('NEW_HIRE', 'New hire'), ('PROMOTION', 'Promotion'), ('OTHER', 'Other')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employeecompetencyrecord',
            name='status',
            field=models.CharField(choices=[('NOT_STARTED', 'Not started'), ('IN_PROGRESS', 'In progress'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('RETRAIN', 'Retrain')], default='NOT_STARTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='examanswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='examtemplate',
            name='position',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('MCQ_SINGLE', 'Multiple Choice (Single Answer)'), ('MCQ_MULTI', 'Multiple Choice (Multiple Answers)'), ('TRUE_FALSE', 'True / False'), ('SHORT_TEXT', 'Short Text'), ('LONG_TEXT', 'Long Text')], default='MCQ_SINGLE', max_length=20),
        ),
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('frequency', models.CharField(choices=[('ONE_TIME', 'One time'), ('YEARLY', 'Yearly'), ('NEW_HIRE', 'New hire'), ('PROMOTION', 'Promotion'), ('OTHER', 'Other')], default='ONE_TIME', max_length=20)),
                ('priority_points', models.PositiveIntegerField(default=0)),
                ('competency_area', models.CharField(blank=True, max_length=100, null=True)),
                ('brand', models.CharField(blank=True, max_length=50, null=True)),
                ('requires_exam', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('content', models.TextField(blank=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='competencies/pdfs/')),
                ('image', models.ImageField(blank=True, null=True, upload_to='competencies/images/')),
                ('external_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competencies_created', to=settings.AUTH_USER_MODEL)),
                ('exam_template', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency', to='training.examtemplate')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='employeecompetencyrecord',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='positioncompetencyrequirement',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='employeecompetencyrecord',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_records', to='training.competency'),
        ),
        migrations.AddField(
            model_name='positioncompetencyrequirement',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_requirements', to='training.competency'),
        ),
        migrations.AlterUniqueTogether(
            name='employeecompetencyrecord',
            unique_together={('employee', 'competency')},
        ),
        migrations.AlterUniqueTogether(
            name='positioncompetencyrequirement',
            unique_together={('position', 'competency')},
        ),
        migrations.RemoveField(
            model_name='employeecompetencyrecord',
            name='best_score',
        ),
        migrations.RemoveField(
            model_name='employeecompetencyrecord',
            name='is_extra_assignment',
        ),
        migrations.RemoveField(
            model_name='employeecompetencyrecord',
            name='last_taken_at',
        ),
        migrations.RemoveField(
            model_name='employeecompetencyrecord',
            name='module',
        ),
        migrations.RemoveField(
            model_name='positioncompetencyrequirement',
            name='min_level_for_position',
        ),
        migrations.RemoveField(
            model_name='positioncompetencyrequirement',
            name='module',
        ),
        migrations.DeleteModel(
            name='TrainingModule',
        ),
    ]
