# Generated by Django 5.2.8 on 2026-01-05 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0007_employeecompetencyrecord_date_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='positioncompetencyrequirement',
            name='competency_level',
        ),
    ]
