# Generated by Django 6.0 on 2026-01-05 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0008_remove_positioncompetencyrequirement_competency_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='examtemplate',
            name='competency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exam_templates', to='training.competency'),
        ),
        migrations.AlterField(
            model_name='competency',
            name='exam_template',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_one', to='training.examtemplate'),
        ),
    ]
