# Generated by Django 6.0 on 2026-01-05 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_id'),
        ('training', '0009_examtemplate_competency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competency',
            name='exam_template',
        ),
        migrations.AddField(
            model_name='positioncompetencyrequirement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='position_requirements', to='branches.branch'),
        ),
    ]
