# Generated by Django 6.0 on 2026-01-05 08:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_user_current_competency_level_and_more'),
        ('branches', '0003_alter_branch_id'),
        ('training', '0010_remove_competency_exam_template_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='positioncompetencyrequirement',
            unique_together={('position', 'competency', 'branch')},
        ),
    ]
