# Generated by Django 5.2.8 on 2026-01-11 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0100_scheduler_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedview',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedulersetting',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
