# Generated by Django 5.2.8 on 2026-01-11 08:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_targets'),
        ('training', '0101_alter_savedview_id_alter_schedulersetting_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeCompetencyRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(blank=True, choices=[('ONE_TIME', 'One time'), ('YEARLY', 'Yearly'), ('NEW_HIRE', 'New hire'), ('PROMOTION', 'Promotion'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('priority_points', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_requirements', to='branches.branch')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_requirements', to='training.competency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='individual_requirements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('employee', 'competency', 'branch')},
            },
        ),
    ]
