# Generated by Django 6.0 on 2026-01-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0102_employeecompetencyrequirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelThresholdSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl1_min_points', models.IntegerField(default=0)),
                ('cl2_min_points', models.IntegerField(default=0)),
                ('cl3_min_points', models.IntegerField(default=0)),
                ('cl4_min_points', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
