# Generated by Django 6.0 on 2026-06-04 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0105_competencyattachment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualCompetencyAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(help_text='Score the employee received on the verbal assessment.')),
                ('max_score', models.FloatField(default=100, help_text='Maximum possible score (defaults to 100).')),
                ('level', models.CharField(blank=True, choices=[('CL0', 'None'), ('CL1', 'Awareness'), ('CL2', 'Knowledge'), ('CL3', 'Skill'), ('CL4', 'Master')], help_text='Optional. If set and the award is approved, this is written to the employee as their competency level override.', max_length=3, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending admin approval'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_awards', to='training.competency')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_awards_received', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(blank=True, help_text='The manager who submitted this award.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_awards_submitted', to=settings.AUTH_USER_MODEL)),
                ('resulting_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_award_source', to='training.employeecompetencyrecord')),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='The admin who approved or rejected.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_awards_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
                'indexes': [models.Index(fields=['status', 'requested_at'], name='training_ma_status_98ec9a_idx'), models.Index(fields=['employee', 'competency'], name='training_ma_employe_b750c4_idx')],
            },
        ),
    ]
